name: Etiscan
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.1.1
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.0
  camera: ^0.11.0+1
  url_launcher: ^6.3.0
  google_fonts: ^6.0.0
  fl_chart: ^0.66.0
  getwidget: ^4.0.0
  syncfusion_flutter_gauges: ^25.2.4
  video_player: ^2.9.0
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  google_sign_in: 6.2.1
  cloud_firestore: 6.0.1  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  change_app_package_name: ^1.1.0


flutter:
  uses-material-design: true

  
  assets:
    - assets/malzemeler.json
    - assets/images/logo.png
    - assets/videos/intro.mp4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png
  adaptive_icon_background: "#FFFFFF"   # İstersen bir renk
  # adaptive_icon_foreground: assets/images/logo.png

flutter_native_splash:
  android: true
  ios: true
  color: "#FFFFFF"
  android_12:
    color: "#FFFFFF"