// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn8dMgs8IGAufnz0v4WWLSvoXaONQjECI',
    appId: '1:201452106191:web:841740257ac0718a83a2ba',
    messagingSenderId: '201452106191',
    projectId: 'etiscan',
    authDomain: 'etiscan.firebaseapp.com',
    storageBucket: 'etiscan.firebasestorage.app',
    measurementId: 'G-KW1VBSFRY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsRB9rjfcszpCKgY8EYe4H0qmAfwBokw4',
    appId: '1:201452106191:android:5a5c19f9323cdace83a2ba',
    messagingSenderId: '201452106191',
    projectId: 'etiscan',
    storageBucket: 'etiscan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqmdMCgcVtr7AP9t-coo4Xt_9NJfSQbD8',
    appId: '1:201452106191:ios:768f47b5f57fc8fe83a2ba',
    messagingSenderId: '201452106191',
    projectId: 'etiscan',
    storageBucket: 'etiscan.firebasestorage.app',
    iosBundleId: 'com.example.mlkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqmdMCgcVtr7AP9t-coo4Xt_9NJfSQbD8',
    appId: '1:201452106191:ios:768f47b5f57fc8fe83a2ba',
    messagingSenderId: '201452106191',
    projectId: 'etiscan',
    storageBucket: 'etiscan.firebasestorage.app',
    iosBundleId: 'com.example.mlkit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn8dMgs8IGAufnz0v4WWLSvoXaONQjECI',
    appId: '1:201452106191:web:6e7c4d77f25a4efb83a2ba',
    messagingSenderId: '201452106191',
    projectId: 'etiscan',
    authDomain: 'etiscan.firebaseapp.com',
    storageBucket: 'etiscan.firebasestorage.app',
    measurementId: 'G-K3BVN2CWNH',
  );
}
